In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [3]:
display(iris_dataset.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [9]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [11]:
print(iris_dataset['target_names'] )

['setosa' 'versicolor' 'virginica']


In [12]:
print(iris_dataset['feature_names'] )

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [14]:
print(type(iris_dataset['data'] ))

<class 'numpy.ndarray'>


In [15]:
print(iris_dataset['data'].shape )

(150, 4)


In [16]:
print(iris_dataset['data'][:5] )

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [19]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(
    iris_dataset['data'] , iris_dataset['target'] , random_state = 0)

In [26]:
display(X_train.shape)
display(y_train.shape)
display(X_test.shape)
display(y_test.shape)

(112, 4)

(112,)

(38, 4)

(38,)

'hoge'